version: "3"

services:
    foxes-dashboard:
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            - FOXES_USERNAME=${FOXES_USERNAME}
            - FOXES_PASSWORD=${FOXES_PASSWORD}
        ports:
            - 8080:3000
        restart: always

    monitor:
        build:
        context: celery-queue
        dockerfile: Dockerfile
        environment:
        # Flower configuration
        - CELERY_BROKER_URL=redis://redis:6379/0
        - FLOWER_PORT=5555
        - FLOWER_BASIC_AUTH=user:password
        ports:
        - "5555:5555"
        entrypoint: flower
        command: -A tasks
        restart: always
        depends_on:
        - worker

    worker:
        build:
        context: celery-queue
        dockerfile: Dockerfile
        volumes:
        - uploads-volume:/flask_app/uploads
        restart: always
        depends_on:
        - redis
    redis:
        image: redis:5.0-alpine
        volumes:
        - redis-volume:/data
        restart: always

volumes:
    uploads-volume:
    redis-volume: