version: "3"

services:
    foxes-dashboard:
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            - FOXES_USERNAME=${FOXES_USERNAME}
            - FOXES_PASSWORD=${FOXES_PASSWORD}
        ports:
            - 8080:3000
        volumes:
            - uploads-volume:/app/flask_app/uploads
        restart: always

    worker:
        build:
            context: ./celery-queue
            dockerfile: Dockerfile
        volumes:
            - uploads-volume:/app/flask_app/uploads
        restart: always
        depends_on:
            - redis

    selenium:
        image: selenium/standalone-chrome
        ports:
            - 4444:4444
        volumes:
            - uploads-volume:/app/flask_app/uploads

    redis:
        image: redis:5.0-alpine
        volumes:
            - redis-volume:/data
        restart: always

volumes:
    uploads-volume:
    redis-volume: